### ISSUE TITLE
Tutorial information is wrong

### ISSUE THREAD

**Issue by cmarchena** [ibm-cloud-academy/ibm-cloud-garage-tdd#2]
Hi!
On "[Stack Kata](https://www.ibm.com/cloud/garage/content/course/test-driven-development/15?task=1)", the information for point 3 on correspond to the prime factors kata. I tried to solve the kata by myself but I consider the first two tests achieve the same. Aren't "starts empty" and "starts with stack size of 0" checking the same?  Shouldn't ` expect(stack.length).toBe(0);` solve both assertions? Or is this one of your little hacker mind tricks? :-D

**Comment by poulzinho** [comment]
@cmarchena For "starts empty" I think you have to create a method called isEmpty(), and for "starts with a stack size of 0" a method size(). Those methods will also help you to prove the assertions "is not empty when pushed" and "stack size is 1 when pushed"

**Comment by lsteck** [comment]
Both the [tutorial](https://www.ibm.com/cloud/architecture/tutorials/introduction-to-test-driven-development) and [course](https://www.ibm.com/cloud/architecture/content/course/test-driven-development/tdd-stack-kata) have been updated.  Thanks!
