### ISSUE TITLE
Where is the package.json file? 

### ISSUE THREAD

**Issue by luiszacheu** [ibm-cloud-academy/ibm-cloud-garage-tdd#3]
I follow the tutorial, but I don't fauld the package.json file in the project.

**Comment by nasastry** [comment]
Got the same issue.

```
% npm install --save-dev jest
npm WARN saveError ENOENT: no such file or directory, open '/Users/nasatry/nasastry-mac/Testing/2016/git_repo/ibm-cloud-garage-tdd/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/nasatry/nasastry-mac/Testing/2016/git_repo/ibm-cloud-garage-tdd/package.json'
npm WARN ibm-cloud-garage-tdd No description
npm WARN ibm-cloud-garage-tdd No repository field.
npm WARN ibm-cloud-garage-tdd No README data
npm WARN ibm-cloud-garage-tdd No license field.

```

**Comment by poulzinho** [comment]
I see that package.json is in .gitignore. So, when you clone the repo it won't be there.

**Comment by nasastry** [comment]
> I see that package.json is in .gitignore. So, when you clone the repo it won't be there.

In that case how to pull that packages.json file? Can you able to change .gitignore ? @poulzinho

**Comment by poulzinho** [comment]
Locally, you could change the .gitignore file, just comment the line package.json. Afterward, you can push your changes to your repo.

For generating the package.json file, follow the guide https://www.ibm.com/cloud/garage/content/course/test-driven-development/11

or, you could create it manually. You can use a similar package.json as the one in my repo https://github.com/poulzinho/ibm-tdd/blob/master/package.json

**Comment by nasastry** [comment]
> Locally, you could change the .gitignore file, just comment the line package.json. Afterward, you can push your changes to your repo.
> 
> For generating the package.json file, follow the guide https://www.ibm.com/cloud/garage/content/course/test-driven-development/11
> 
> or, you could create it manually. You can use a similar package.json as the one in my repo https://github.com/poulzinho/ibm-tdd/blob/master/package.json

Thank you very much `https://github.com/poulzinho/ibm-tdd/blob/master/package.json` this helped. @poulzinho

**Comment by lsteck** [comment]
When you run the `npm init -y` command in the **Setup you project**  section of the README it will create the package.json file.
