### ISSUE TITLE
npm install --save-dev jest fails

### ISSUE THREAD

**Issue by osmanburucu-ibm** [ibm-cloud-academy/ibm-cloud-garage-tdd#5]
[2020-05-08T10_41_47_968Z-debug.log](https://github.com/ibm-cloud-academy/ibm-cloud-garage-tdd/files/4598596/2020-05-08T10_41_47_968Z-debug.log)
~/git/ibm-cloud-garage-tdd   master  npm install --save-dev jest
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN jsdom@16.2.2 requires a peer of canvas@^2.5.0 but none was installed.
npm WARN ws@7.2.5 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.2.5 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: jsdom@16.2.2 (node_modules/jsdom):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: EEXIST: file already exists, mkdir '/Users/ozzy/git/ibm-cloud-garage-tdd/node_modules/.staging/jsdom-94824825/lib/jsdom/living/generated'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: File exists: /Users/ozzy/git/ibm-cloud-garage-tdd/node_modules/.staging/jsdom-94824825/lib/jsdom/living/generated
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lodash@4.17.15 (node_modules/lodash):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/Users/ozzy/git/ibm-cloud-garage-tdd/node_modules/.staging/lodash-c4d8c21d/fp/assignAll.js'

npm ERR! path /Users/ozzy/git/ibm-cloud-garage-tdd/node_modules/.staging/char-regex-b7144f72/index.d.ts
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
npm ERR! Error: EACCES: permission denied, open '/Users/ozzy/git/ibm-cloud-garage-tdd/node_modules/.staging/char-regex-b7144f72/index.d.ts'
npm ERR!  { Error: EACCES: permission denied, open '/Users/ozzy/git/ibm-cloud-garage-tdd/node_modules/.staging/char-regex-b7144f72/index.d.ts'
npm ERR!   cause:
npm ERR!    { Error: EACCES: permission denied, open '/Users/ozzy/git/ibm-cloud-garage-tdd/node_modules/.staging/char-regex-b7144f72/index.d.ts'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'open',
npm ERR!      path: '/Users/ozzy/git/ibm-cloud-garage-tdd/node_modules/.staging/char-regex-b7144f72/index.d.ts' },
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/Users/ozzy/git/ibm-cloud-garage-tdd/node_modules/.staging/char-regex-b7144f72/index.d.ts',
npm ERR!   parent: 'ibm-cloud-garage-tdd' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ozzy/.npm/_logs/2020-05-08T10_41_47_968Z-debug.log

then i run sudo npm install --save-dev jest 
no errors

Change the Package.json as described in readme.. then run 

 npm test

> ibm-cloud-garage-tdd@1.0.0 test /Users/ozzy/git/ibm-cloud-garage-tdd
> jest --verbose

/Users/ozzy/git/ibm-cloud-garage-tdd/node_modules/find-up/index.js:29
		const foundPath = await runMatcher({...options, cwd: directory});
		                                    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ozzy/git/ibm-cloud-garage-tdd/node_modules/pkg-dir/index.js:3:16)

**Comment by kylegoetz** [comment]
I'm getting the exact same error with the exact same package (`char-regex-b7144f72`)

It's a dependency of a dependency, so I can't change my dependencies to avoid it. `npm i` fails with a very similar error at the same path (`/path/to/my/project/node_modules/.staging/char-regex-b7144f72`)
